//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLUIS.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyLUIS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似  !#$%&amp;&apos;()+,-.0123456789;=@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]^_`abcdefghijklmnopqrstuvwxyz{}~§©¬®°±²·º»ÁÈÉÔÖ×Üàâäêíñó÷úćĐĒˇˊˋ˙˚̂̍ΔΩαβγκμπЂЕНОавгиклмрћกขดตทนบยรวศสหอะัาิีเแạ–—―‘’‚“”•․…‧′‵※€℃™ⅡⅢⅦ←↑→↓↘∕√∞∣∶∼≈⋯─│╱╲▇▉▋▍▎■□▲△▶▷►▼◄◆◇○◎●☀★☆☉☛☞♀♠♥♦✂✈✓✔✨✿❄❤➜➡➲⬇⼂、。〇〒〜〝〞〫〱〺ぁあぃいぅうぇえぉおかがきぎくぐけげこごさざしじすずせぜそぞただちぢっつづてでとどなにぬねのはばぱひびぴふぶぷへべぺほぼぽまみむめもゃやゅゆょよらりるれろわをん゛゜ゝゞァアィイゥウェエォオカガキギクグケゲコゴサザシジスズセゼソゾタダチヂッツヅテデトドナニヌネノハバパヒビピフブプヘベペホボポマミムメモャヤュユョヨラリルレロワヱヲンヴヶ・ーヽヾㄅㄆㄇㄈㄉㄊㄋㄌㄍㄎㄏㄐㄑㄒㄓㄔㄕㄖㄗㄘㄙㄚㄛㄜㄝㄞㄟㄠㄡㄢㄣㄤㄥㄦㄧㄨㄩ㊣㑹㨗㪈䄂䕶䠷一丁丂七丄丅丆万丈三上下丌不与丏丐丑丒专且丕世丗丘丙业丛东丝丞丟丠両丢丣两严並丧丨丩 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        public static string charlist {
            get {
                return ResourceManager.GetString("charlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        public static byte[] embed {
            get {
                object obj = ResourceManager.GetObject("embed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 打開app應用
        ///詢問公車路線
        ///數學計算
        ///閒聊
        ///詢問電影場次
        ///查詢聯絡人
        ///查詢食譜
        ///詢問日期
        ///電子郵件指令
        ///詢問電視節目
        ///詢問航班
        ///詢問健康資訊
        ///詢問樂透
        ///詢問地圖
        ///詢問足球賽事
        ///簡訊指令
        ///音樂指令
        ///詢問新聞
        ///詢問小說
        ///詢問詩詞
        ///詢問廣播節目
        ///詢問謎語
        ///鬧鐘時程設定
        ///詢問股票
        ///電話指令
        ///詢問火車班次
        ///詢問翻譯
        ///切換電視頻道
        ///影片播放指令
        ///詢問天氣
        ///開啟網站 的當地語系化字串。
        /// </summary>
        public static string intent_list {
            get {
                return ResourceManager.GetString("intent_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        public static byte[] text_cnn {
            get {
                object obj = ResourceManager.GetObject("text_cnn", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
